name: deploy-qa

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SF_USERNAME: ${{ secrets.SF_USERNAME }}
  SF_ROLE: ${{ secrets.SF_ROLE }}
  SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
  SF_DATABASE: ${{ secrets.SF_QA_DATABASE }}
  SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master
          
      - name: Download SnowSQL
        run:  curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
      #- name: Install SnowSQL
      #  run: |
      #    curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
      #    SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash      
        
      #- name: Install SnowSQL          
      #  run: SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
        
      - name: Test installation
        run:  ~/snowflake/snowsql -v 

      # create backup objects
      - name: Execute Create Backups SQL Against Snowflake
        id: sql_execute_create_baks
        #run: ~/snowflake/snowsql -f 00-back-ups.sql -a $SF_ACCOUNT -u $SF_USERNAME -P $SF_PASSWORD -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE
        run: ~/snowflake/snowsql -f 00-back-ups.sql
